[package]
name = "portty-builtins"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
portty-ipc = { path = "../ipc" }
serde = "1"
clap = { version = "4", features = ["derive"] }


[[bin]]
name = "portty-builtin"
path = "src/main.rs"
