[package]
name = "portty"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "portty"
path = "src/main.rs"

[dependencies]
libportty = { path = "../lib" }
clap = { version = "4", features = ["derive"] }
