[package]
name = "portty-types"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.12.0"
zvariant = { version = "5.8.0", features = ["option-as-array"] }
serde = { version = "1", features = ["derive"] }
futures-util = "0.3"
bincode = "1"
